---
title: "WISER Public"
author: "Department of Evironmental Health Science, University of Georgia"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  epuRate::epurate:
    toc: TRUE
    number_sections: FALSE
    code_folding: "show"
---

# Updates Coming Soon! {#Announcements}

## What is WISER
 <font size="4">Wastewater Informatics for SARS-CoV-2 Epidemiology Research or WISER, is an ongoing collaborative research project at the University of Georgia conducted through College of Public Health and College of Veterinary Medicine. This project is designed to optimize the use of wastewater-based epidemiology (WBE) methods for the monitoring and sequencing of SARS-CoV-2 RNA at the community level. WBE is a technique which utilizes municipal wastewater sampling to elucidate the burden of a disease of interest in the population. Using these methods, wastewater samples can be taken to represent the "sewershed" (a municipal area of interest), and the trends of SARS-CoV-2 transmission within the community can be estimated. Furthermore, analysis of viral genomes from these massively pooled sewage samples,  can help discover the emergence and spread of distinct SARS-CoV-2 variants, identify known variants of concern, and  track potential novel variants that may be subject to vaccine escape at the community level. While methods are still being developed, WBE stands as a robust supplement to traditional clinical testing due to that fact that community sampling is unbiased towards testing data.</font>

## Participating Labs {.tabset}
### Bahl Lab
 <font size="3">Under the Direction of Dr. Justin Bahl, the Bahl Lab specializes in molecular epidemiology of viral systems.Using the data collected some wastewater sequencing, Dr. Bahl and his students aim to characterize the movement and transmission of SARS-CoV-2 variants. From this, spatial transmission models will be developed to study the molecular evolution and mechanisms of viral spread within the study community.</font> 

### Glenn Lab
 <font size="3">Under the direction of Dr. Travis Glenn, the Glenn lab specializes in genomic sequencing and bioinformatics. Using their established methods, Dr. Glenn and his students aim to develop and optimize methods to sequence and identify SARS-CoV-2 variants from collected wastewater.</font>

### Lipp Lab
 <font size="3">Under the direction of Dr. Erin Lipp, the Lipp lab specializes in aquatic environmental microbiology. Since June 2020, Dr. Lipp and her students have been working to develop a pipeline for the collection, identification, and quantification of SARS-CoV-2 in municipal wastewater. Using their established methods, the Lipp lab aims to continue this collection process while developing a standardized sample concentration method to improve genomic sequencing outcomes from wastewater sampling.</font>

### Sanchez Lab
 <font size="3">Under the direction of Dr. Susan Sanchez, the Sanchez lab specializes the diagnostic testing and clinical identification of various infectious disease. Since spring 2020, the Sanchez lab has served as an integral part UGA's response to the pandemic by providing students and staff with survillence testing services on campus. Through this work, the Sanchez lab has accumulated a library of clinical SARS-CoV-2 samples from various time points throughout the pandemic and aims to serve as the clinical arm of the WISER project to complement wastewater sampling.</font>

## Project Objectives
_Coming Soon_   

## Key Findings to Date
_Coming Soon_  


## Section 2 {.tabset}

Formatting examples below




***

| Tables        | Test           | Text  |
| ------------- |:-------------:| -----:|
| samp 1      | value 1 | x |
| samp2       | value 2 | y |
| samp3       | value 3 | z |

***



### tab 1
test

### tab 2
_test_